<!-- service.phtml -->
<div class="container container-fluid">
    <div class="row row-offcanvas row-offcanvas-left">
        <div class="col-6 col-md-3 sidebar-offcanvas" id="sidebar">
            <ul class="list-group">
                <?php foreach ($moduleList as $item): ?>
                <li class="list-group-item">
                    <a href="<?=$item['url']?>"><?=$item['moduleName']?></a>
                    <small class="text-muted"><?=$item['summary']?></small>
                </li>
                <?php endforeach;?>
            </ul>
        </div>
        <div class="col-12 col-md-9"><article class="markdown-body"><?=$markup?></article></div>
    </div>
</div>
<!-- ./service.phtml -->